FROM node:10

WORKDIR /app
COPY . .

RUN yarn && yarn add moment && yarn add vis-util && npm run build-dev --prod --build-optimizer
RUN npm run compress:brotli

WORKDIR /app/dist
COPY assets www/en/
RUN npm install --production
EXPOSE 3004

CMD [ "npm", "run", "serve:prod" ]
